### ISSUE TITLE
Defunct project website

### ISSUE THREAD

**Issue by CvX** [spencer516/ember-functional-modifiers#13]
The [`homepage` field in the `package.json` file](https://github.com/spencer516/ember-functional-modifiers/blob/59b93ec/package.json#L76) leads to a defunct website:

<img alt="invalid page" src="https://user-images.githubusercontent.com/66961/54923907-82d8ed80-4f0b-11e9-876b-129b1516876a.png" width="440">

**Comment by spencer516** [comment]
Thanks!
